Repository Cropi/usbguard-notifier, pull requests merged in 2019-08, with the labels that each got.

#5 usbgbuard::exception handler added + waiting option
  scripts/restyle.sh
  src/Main.cpp
Labels: enhancement

#6 wrapper class for libnotify added
  src/NotifyWrapper.hpp
Labels: enhancement

#7 new format style
  scripts/restyle.sh
  src/Log.cpp
  src/Log.hpp
  src/Main.cpp
  src/Notifier.cpp
  src/Notifier.hpp
  src/NotifyWrapper.hpp
Labels: enhancement

#11 .travis.yml added
  .travis.yml
Labels: enhancement, help wanted

#12 notification concept
  src/Main.cpp
  src/Notifier.cpp
  src/Notifier.hpp
  src/NotifyWrapper.hpp
Labels: enhancement

#14 Add usbguard icon
  Makefile.am
  configure.ac
  icons/usbguard-icon.svg
  src/Notifier.cpp
Labels: enhancement

#15 icon path bug fixed
  Makefile.am
Labels: bug

#16 Fix --help bug
  src/Main.cpp
Labels: bug

#17 Added several usability improvements
  Makefile.am
  README.md
  configure.ac
  usbguard_notifier.service.in
Labels: enhancement

#23 load icon in binary
  Makefile.am
  configure.ac
  src/Notifier.cpp
  src/Notifier.hpp
  src/NotifyWrapper.hpp
Labels: enhancement

#25 Debug mode can be turned on/off via --debug argument
  .gitignore
  man/usbguard-notifier.1.adoc
  src/Log.cpp
  src/Log.hpp
  src/Main.cpp
Labels: enhancement
